wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=121477
     - WORDPRESS_DB_USER=root
    ports:
     - "192.168.100.103:7878:80"
    volumes:
     - ./html:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=121477
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
